### ISSUE TITLE
Update of "requirements.txt" needed for Python 3.12.0

### ISSUE THREAD

**Issue by AndreasWagnerBerlin** [Pyrokahd/Fenecon-Solar-Dashboard#1]
Both files "requirements.txt" list 
"numpy==**1.24.3**".

Python 3.12.0 (Oct. 02 -2023) does not digest that version and throws an error when building a docker container.
Recommendation:
update to  "numpy==**1.26.2**"
With this change both docker containers are build.
I cannot verify any side effects of the new numpy version at the moment.

**Comment by Pyrokahd** [comment]
Thanks for letting me know. I upgraded it to 1.26.2.
